<?php


	namespace C3\C3baxi\Persistence\Generic;


	use C3\C3baxi\Domain\Model\Fahrt;
	use C3\C3baxi\Domain\Model\Haltestelle;
	use C3\C3baxi\Domain\Model\Linie;
	use TYPO3\CMS\Extbase\Utility\DebuggerUtility;

	class QueryFactory extends \TYPO3\CMS\Extbase\Persistence\Generic\QueryFactory {

		public function create( $className ) {
			$query = parent::create( $className ); // TODO: Change the autogenerated stub


			$cron = false;
			if( $GLOBALS['c3baxi'] === 'REPORT' ) {
				$cron = is_a($className, Haltestelle::class, true) || is_a($className, Fahrt::class, true);
			}

			if( is_a( $className, Linie::class, TRUE) || $cron ) {
				$querySettings = $query->getQuerySettings();
				$querySettings->setIgnoreEnableFields(true);
			}

			return $query;
		}
	}