<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "c3baxi"
 *
 * Auto generated by Extension Builder 2019-06-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Baxi Fahrten',
    'description' => '',
    'category' => 'be',
    'author' => '',
    'author_email' => '',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
            'femanager' => '1.0.0-',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
