<?php
namespace C3\Local\ViewHelpers;

use TYPO3Fluid\Fluid\Core\Rendering\RenderingContextInterface;
use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;

	class DatepickerViewHelper extends AbstractViewHelper
	{
		protected $escapeOutput = false;

		public function initializeArguments()
		{
//			parent::initializeArguments(); // TODO: Change the autogenerated stub
			$this->registerArgument( 'max', 'integer', '');
			$this->registerArgument( 'min', 'integer', '');
			$this->registerArgument( 'step', 'integer', '');
		}

		public static function renderStatic( array $arguments, \Closure $renderChildrenClosure, RenderingContextInterface $renderingContext )
		{
//			return parent::renderStatic( $arguments, $renderChildrenClosure, $renderingContext ); // TODO: Change the autogenerated stub
			return var_export( $arguments, 1 );
		}
	}