<?php


	namespace C3\C3baxi\ViewHelpers\Route;


	use C3\C3baxi\ViewHelpers\IconViewHelper;
	use C3\C3baxi\ViewHelpers\StationViewHelper;
	use TYPO3Fluid\Fluid\Core\Rendering\RenderingContextInterface;
	use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;

	class SelectedViewHelper extends AbstractViewHelper {

		protected $escapeOutput = FALSE;

		public function initializeArguments() {
			parent::initializeArguments(); // TODO: Change the autogenerated stub
			$this->registerArgument( 'start', 'object', 'Fahrt Anfang' );
			$this->registerArgument( 'end', 'object', 'Fahrt ende' );
			$this->registerArgument( 'time', 'string', 'Zeit' );
			$this->registerArgument( 'fahrt', 'object', 'Fahrt' );
		}

		public static function renderStatic( array $arguments, \Closure $renderChildrenClosure, RenderingContextInterface $renderingContext ) {
			$fahrt = $arguments['fahrt'];
			$zeiten = $fahrt->getZeiten();
			$abfahrt = $ankunft = 0;

			foreach ( $zeiten as $zeit ) {
				if ( $zeit->getZone() === $arguments['start']->getZone() ) {
					$abfahrt = $zeit;
				}

				if ( $zeit->getZone() === $arguments['end']->getZone() ) {
					$ankunft = $zeit;
				}

				if ( $abfahrt != 0 && $ankunft != 0 ) break;
			}

			$duration = $ankunft->getZeit() - $abfahrt->getZeit();
			$uidx = -1;
			$units = [
				'Minuten',
				'Stunden'
			];
			while ( $duration > 60 ) {
				$duration = $duration / 60;
				$uidx++;
			}

			$duration = 'ca. ' . $duration . ' ' . $units[$uidx];

			$linie = $arguments['fahrt']->getLinie();

			$result = '<div class="box">';
			$result .= '<div class="box-content route route--selected">';
			$result .= '<div class="route-station">';
			$result .= '<p>' . $arguments['start']->getName()
				. '<small>Abfahrt: ab ' . date( 'H:i', $abfahrt->getZeit() ) . '</small>'
				. '</p>';
			$result .= '</div>';
			$result .= '<div class="route-info">'
				. '<span><svg class="icon" width="16" height="16"><use xlink:href="#BAXI"/></svg>&nbsp;' . $linie->getNr() . '</span>'
				. '<span><svg class="icon" width="16" height="16"><use xlink:href="#Uhr_kontur"/></svg>&nbsp;' . $duration . '</span>'
				. '</div>';
			$result .= '<div class="route-station">';
			$result .= '<p>' . $arguments['end']->getName()
				. '<small>Ankunft: ab ' . date( 'H:i', $ankunft->getZeit() ) . '</small>'
				. '</p>';
			$result .= '</div>';
			$result .= '</div>';
//			$result .= StationViewHelper::renderStatic( ['station' => $arguments['start']], $renderChildrenClosure, $renderingContext );
			$result .= '<div class="box-footer">';
			$result .= '<p data-action="help" data-question="1">' . IconViewHelper::renderStatic( ['name' => 'Hilfe_Klein'], $renderChildrenClosure, $renderingContext ) . '&nbsp;Wieso sind die Zeitangaben nicht genauer?</p>';
			$result .= '</div>';
			$result .= '<span class="bubble"></span></div>';
			return $result;
		}

	}