<?php


	namespace C3\C3baxi\ViewHelpers;


	use TYPO3\CMS\Fluid\Core\ViewHelper\AbstractTagBasedViewHelper;
	use TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper;
	use TYPO3Fluid\Fluid\Core\Rendering\RenderingContextInterface;


	class IconViewHelper extends AbstractViewHelper
	{

		protected $escapeOutput = FALSE;

//		protected $tagName = 'svg';

		public function initializeArguments()
		{
			parent::initializeArguments(); // TODO: Change the autogenerated stub
			$this->registerArgument( 'name', 'string', 'Icon Name', TRUE );
			$this->registerArgument( 'class', 'string', 'Class Name' );
			$this->registerArgument( 'width', 'integer', 'Width' );
			$this->registerArgument( 'height', 'integer', 'Height' );
		}

		public static function renderStatic( array $arguments, \Closure $renderChildrenClosure, RenderingContextInterface $renderingContext )
		{
			$name = $arguments['name'];
			$class = $arguments['class'];
			$width = $arguments['width'];
			$height = $arguments['height'];
			return '<svg class="icon ' . $class . '" '
				. ($width ? 'width="'.$width.'" ' : null )
				. ($height ? 'height="'.$height.'"' : null ) . '>'
				. '<use xlink:href="#' . $name . '" fill="currentColor" /></svg>';
		}

	}