<?php


	namespace C3\C3baxi\ViewHelpers;

	use TYPO3Fluid\Fluid\Core\Rendering\RenderingContextInterface;
	use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;

	use C3\C3baxi\ViewHelpers\StationViewHelper;

	class RouteViewHelper extends AbstractViewHelper
	{

		protected $escapeOutput = FALSE;

		function initializeArguments()
		{
			parent::initializeArguments(); // TODO: Change the autogenerated stub
			$this->registerArgument( 'start', 'object', 'Fahrt Anfang' );
			$this->registerArgument( 'end', 'object', 'Fahrt ende' );
			$this->registerArgument( 'time', 'string', 'Zeit' );
		}

		public static function renderStatic( array $arguments, \Closure $renderChildrenClosure, RenderingContextInterface $renderingContext )
		{
//			return parent::renderStatic( $arguments, $renderChildrenClosure, $renderingContext ); // TODO: Change the autogenerated stub
			$result = '<div class="box route">
  <div class="route-station">
    <p><small>Von</small></p>
    <p>' . StationViewHelper::renderStatic( ['station' => $arguments['start']], $renderChildrenClosure, $renderingContext ) . '</p>
  </div>
  <div class="route-station">
    <p><small>Bis</small></p>
    <p>' . StationViewHelper::renderStatic( ['station' => $arguments['end']], $renderChildrenClosure, $renderingContext ) . '</p>
  </div>
  <footer class="box-footer">
    <span data-action="help" data-question="2">'. IconViewHelper::renderStatic( ['name'=>'Hilfe_Klein'], $renderChildrenClosure, $renderingContext).'&nbsp;Was ist eine Gebietszone?</span>
  </footer>
  <span class="bubble"></span>
</div>';


			return $result;
		}

	}