<?php


	namespace C3\C3baxi\ViewHelpers;


	use TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper;
	use TYPO3Fluid\Fluid\Core\Rendering\RenderingContextInterface;

	class UserViewHelper extends AbstractViewHelper {

		function initializeArguments() {
			parent::initializeArguments(); // TODO: Change the autogenerated stub
			$this->registerArgument( 'userid', 'integer', 'UserId' );
		}

		public static function renderStatic( array $arguments, \Closure $renderChildrenClosure, RenderingContextInterface $renderingContext ) {
			$objectManager = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance( 'TYPO3\\CMS\\Extbase\\Object\\ObjectManager' );
			$userRepo = $objectManager->get( 'C3\\C3baxi\\Domain\\Repository\\UserRepository' );
			$user = $userRepo->findByUid( $arguments['userid'] );
			return $user->getName() . '(' . $user->getEmail() . ')';
//			return parent::renderStatic( $arguments, $renderChildrenClosure, $renderingContext ); // TODO: Change the autogenerated stub
		}
	}